source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HBProgressSAH_Example', :exclusive => true do
  pod 'HBProgressSAH', '~> 0.1.0'
end

target 'HBProgressSAH_Tests', :exclusive => true do
  pod 'HBProgressSAH', '~> 0.1.0'

  pod 'FBSnapshotTestCase'
end
